# Gradient and Hessian approximation

In [211]:
import numpy as np
import decimal
from decimal import Decimal

<h2 style="color:rgb(0,0,0)">Problem function definition and starting points</h2>

In [212]:
def f_1(x):
    return ((100 * ((x[1]-x[0]**2)**2)) + ((1-x[0])**2))

def f_2(x):
    return (150 * ((x[0]*x[1])**2)) + ((Decimal(0.5)*x[0] + 2*x[1] - 2)**2)

x_0_01 = np.array([Decimal(1.2),Decimal(1.2)])
x_0_02 = np.array([Decimal(-1.2),Decimal(1)])
x_0_03 = np.array([Decimal(0.2),Decimal(0.8)])
x_0_11 = np.array([Decimal(-0.2),Decimal(1.2)])
x_0_12 = np.array([Decimal(3.8),Decimal(0.1)])
x_0_13 = np.array([Decimal(1.9),Decimal(0.6)])

<h2 style="color:rgb(0,0,0)">Gradient estimation</h2>

In [387]:
eps_grad = Decimal(0.0000000000000001)

In [438]:
# use to get gradient as np.array
def grad_estimate_np(f, x: np.array, eps: decimal.Decimal):
    grad=np.full(len(x), Decimal(0))
    for i in range(len(x)):
        unit_vector = np.full(len(x), Decimal(0))
        unit_vector[i] = Decimal(1)
        grad[i] = round(float((f(x + (eps * unit_vector)) - f(x)) / eps), 9)
    return np.array(grad)

# use for further calculation of hessian estimate
def grad_estimate(f, x: np.array, eps: decimal.Decimal):
    grad=np.full(len(x), Decimal(0))
    for i in range(len(x)):
        unit_vector = np.full(len(x), Decimal(0))
        unit_vector[i] = Decimal(1)
        grad[i] = (f(x + (eps * unit_vector)) - f(x)) / eps
    return np.array(grad)

In [436]:
print('Estimated gradient of function 1 at x0=[1.2, 1.2]:  ',grad_estimate_np(f_1,x_0_01, eps_grad)) #true [115.6, -48.0]
print('Estimated gradient of function 1 at x0=[-1.2, 1]:   ',grad_estimate_np(f_1,x_0_02, eps_grad)) #true [-215.6 -88.0]
print('Estimated gradient of function 1 at x0=[0.2, 0.8]:  ',grad_estimate_np(f_1,x_0_03, eps_grad)) #true [-62.4 152.0]
print('\n')
print('Estimated gradient of function 2 at x0=[-0.2, 1.2]: ',grad_estimate_np(f_2,x_0_11, eps_grad)) #true [-86.1  15.6]
print('Estimated gradient of function 2 at x0=[3.8, 0.1]:  ',grad_estimate_np(f_2,x_0_12, eps_grad)) #true [11.5 433.6]
print('Estimated gradient of function 2 at x0=[1.9, 0.6]:  ',grad_estimate_np(f_2,x_0_13, eps_grad)) #true [205.35 650.4]

Estimated gradient of function 1 at x0=[1.2, 1.2]:   [115.6 -48.0]
Estimated gradient of function 1 at x0=[-1.2, 1]:    [-215.6 -88.0]
Estimated gradient of function 1 at x0=[0.2, 0.8]:   [-62.4 152.0]


Estimated gradient of function 2 at x0=[-0.2, 1.2]:  [-86.1 15.6]
Estimated gradient of function 2 at x0=[3.8, 0.1]:   [11.5 433.6]
Estimated gradient of function 2 at x0=[1.9, 0.6]:   [205.35 650.4]


<h2 style="color:rgb(0,0,0)">Hessian estimation</h2>

In [ ]:
eps_hess = Decimal(0.00000001)

In [416]:
def hessian_estimate(f, x: np.array, eps_hess: decimal.Decimal, eps_grad):
    hessian = np.full((len(x), len(x)), Decimal(0))
    for i in range(len(x)):
        unit_vector = np.full(len(x), Decimal(0))
        unit_vector[i] = Decimal(1)
        hessian[:, i] = np.array([round(float(g),9) for g in (np.divide(grad_estimate(f=f, x=(x + (eps_hess * unit_vector)), eps=eps_grad) - grad_estimate(f=f, x=x, eps=eps_grad), eps_hess))])
    return hessian

In [437]:
print('Estimated hessian of function 1 at x0=[1.2, 1.2]: \n',
      hessian_estimate(f_1,x_0_01, eps_hess, eps_grad),'\n') #true [[1250,-480],[-480,200]]
print('Estimated hessian of function 1 at x0=[-1.2, 1]: \n',
      hessian_estimate(f_1,x_0_02, eps_hess, eps_grad),'\n') #true [[1330,480],[480,200]]
print('Estimated hessian of function 1 at x0=[0.2, 0.8]: \n',
      hessian_estimate(f_1,x_0_03, eps_hess, eps_grad),'\n') #true [[-270,-80],[-80,200]]
print('\n')
print('Estimated hessian of function 2 at x0=[-0.2, 1.2]: \n',
      hessian_estimate(f_2,x_0_11, eps_hess, eps_grad),'\n') #true [[432.5,-142],[-142,20]]
print('Estimated hessian of function 2 at x0=[3.8, 0.1]: \n',
      hessian_estimate(f_2,x_0_12, eps_hess, eps_grad),'\n') #true [[3.5,230],[230,4340]]
print('Estimated hessian of function 2 at x0=[1.9, 0.6]: \n',
      hessian_estimate(f_2,x_0_13, eps_hess, eps_grad),'\n') #true [[108.5,686],[686,1091]]

Estimated hessian of function 1 at x0=[1.2, 1.2]: 
 [[1250.0 -480.0]
 [-480.0 200.0]] 

Estimated hessian of function 1 at x0=[-1.2, 1]: 
 [[1330.0 480.0]
 [480.0 200.0]] 

Estimated hessian of function 1 at x0=[0.2, 0.8]: 
 [[-270.0 -80.0]
 [-80.0 200.0]] 



Estimated hessian of function 2 at x0=[-0.2, 1.2]: 
 [[432.492 -142.008]
 [-142.008 19.992]] 

Estimated hessian of function 2 at x0=[3.8, 0.1]: 
 [[3.51 230.01]
 [230.01 4340.01]] 

Estimated hessian of function 2 at x0=[1.9, 0.6]: 
 [[108.5 686.0]
 [686.0 1091.0]] 

